### ISSUE TITLE
Adding better-monadic-for

### ISSUE THREAD

**Issue by TonioGela** [typelevel/ce3.g8#13]
What about adding better-monadic-for? Documentation [_highly_](https://typelevel.org/cats-effect/docs/getting-started) suggest it for scala 2. If the scala version gets parametrized **probably** it can be disabled for scala 3 builds.

**Comment by kubukoz** [comment]
I think it should be added, yeah. We can worry about disabling it once someone adds a Scala 3 mode. Would you mind making an issue for that? (also, feel free to submit the bm4 addition)

**Comment by TonioGela** [comment]
> Would you mind making an issue for that?

Isn't this an issue? 🤔
Btw in a sec I'll PR.

**Comment by kubukoz** [comment]
I meant for the Scala version selection :)

**Comment by TonioGela** [comment]
> I meant for the Scala version selection :)

Added #15

**Comment by kubukoz** [comment]
Thanks :)

**Comment by TonioGela** [comment]
Can't this one be closed?

**Comment by kubukoz** [comment]
Yeah
