### ISSUE TITLE
Optionally Remove better-monadic-for for Scala3

### ISSUE THREAD

**Issue by TonioGela** [typelevel/ce3.g8#15]
Whenever a Scala 3 mode will be available for g8 it would be awesome to do not include better-monadic-for as a plugin.

**Comment by TonioGela** [comment]
At the moment [conditionals are supported in g8](http://www.foundweekends.org/giter8/Combined+Pages.html#Conditionals) but [it cannot test for attributes](https://github.com/antlr/stringtemplate4/blob/master/doc/templates.md#discussion-2) like `scala_version==2.13.5` neither something like `scala_version.startsWith(2)`.
Behaviours can be enable/disable adding a boolean parameter like `scala2 = yes` in the default.properties (with a default too) but it would require human interaction (i.e. answering yes or no) during template resolution. 
It can be solved this way or just waiting for a g8 (or even sbt) enhancement.

**Comment by kubukoz** [comment]
I think `scala3 = no` would be best as a default, also `scala2=yes` doesn't clearly state what the alternative is 🤔 

> but it would require human interaction (i.e. answering yes or no) during template resolution

wdym? We already ask for the project name, so there's human interaction involved
